### PR TITLE
Init Hack@AC Writeup Page (#65)

### PR DESCRIPTION
**Pull request by Kairos-T**

### CODE REVIEW

**Review by notbowen — APPROVED** [review]
Smash or pass? Smash.

**Comment by Kairos-T** [comment]
> Smash or pass? Smash.

are you ok??? @notbowen

**Comment by notbowen** [comment]
absolutely NOT

**Comment by notbowen** [comment]
i'm bowen 😄

**Comment by Kairos-T** [comment]
thats heckin crazy man...

**Pull request merged**
