### PR TITLE
Added ability to list authors

### PR DESCRIPTION
**Pull request by notbowen**
@Kairos-T can check if I got leave any files out/screw anything up

### CODE REVIEW

**Review by Kairos-T — COMMENTED** [review]
I think this looks good, but I was thinking of putting the authors before the members  tab since all the taxanomies are in the middle :O not sure,, thoughts?

**Comment by notbowen** [comment]
Would "writeups", "members" followed by the rest of the taxonomies be ok? It feels nicer to see the member page in front since it has more content :man_shrugging:

**Comment by Kairos-T** [comment]
oh yeah i think that makes more sense

**Comment by notbowen** [comment]
aight lemme change the order rq

**Comment by notbowen** [comment]
writeups, members, tags, CTFs, authors?

**Comment by Kairos-T** [comment]
yep sounds good

**Review by Kairos-T — APPROVED** [review]

**Comment by Kairos-T** [comment]
@notbowen do the honours :D

**Comment by Kairos-T** [comment]
huat ah

**Comment by notbowen** [comment]
wooo

**Pull request merged**
