### PR TITLE
added README.md for the repo

### PR DESCRIPTION
**Pull request by Kairos-T**

### CODE REVIEW

**Comment by Kairos-T** [comment]
@notbowen I added a README.md for this repo to provide clarity on this repo and 404 in general, pls give feedback thks!

**Comment by notbowen** [comment]
There's an extra "p" at the hugo installation part :joy:

**Comment by notbowen** [comment]
But other than that it looks amazing :+1:

**Review by notbowen — APPROVED** [review]
Its ok I fixed it :+1:

**Comment by Kairos-T** [comment]
oh oops i did not see that

and also i tried to fix it but u did and now i have conflicts x.x

**Comment by Kairos-T** [comment]
huat ah

**Pull request merged**
