### PR TITLE
uhhhh i uploaded my stuff i think i hope its correct

### PR DESCRIPTION
**Pull request by Callum-HQ**

### CODE REVIEW

**Review by Kairos-T — COMMENTED** [review]
LGTM

**Review by Kairos-T — APPROVED** [review]

**Comment by notbowen** [comment]
Looks valid, but why did u change Galen's link :joy:

**Comment by Callum-HQ** [comment]
i did??

**Comment by Callum-HQ** [comment]
image

confuse

**Comment by Callum-HQ** [comment]
github is trippin

**Pull request merged**
